% \VignetteIndexEntry{rmongodb Cheat Sheet}

\documentclass[10pt,landscape]{article}
\usepackage{multicol}
\usepackage{calc}
\usepackage{ifthen}
\usepackage[landscape]{geometry}
\usepackage{hyperref}

% following the layout by http://stdout.org/~winston/latex/latexsheet.tex

% This sets page margins to .5 inch if using letter paper, and to 1cm
% if using A4 paper. (This probably isn't strictly necessary.)
% If using another size paper, use default 1cm margins.
\ifthenelse{\lengthtest { \paperwidth = 11in}}
  { \geometry{top=.5in,left=.5in,right=.5in,bottom=.5in} }
	{\ifthenelse{ \lengthtest{ \paperwidth = 297mm}}
		{\geometry{top=1cm,left=1cm,right=1cm,bottom=1cm} }
		{\geometry{top=1cm,left=1cm,right=1cm,bottom=1cm} }
	}

% Turn off header and footer
\pagestyle{empty}
 

% Redefine section commands to use less space
\makeatletter
\renewcommand{\section}{\@startsection{section}{1}{0mm}%
                                {-1ex plus -.5ex minus -.2ex}%
                                {0.5ex plus .2ex}%x
                                {\normalfont\large\bfseries}}
\renewcommand{\subsection}{\@startsection{subsection}{2}{0mm}%
                                {-1explus -.5ex minus -.2ex}%
                                {0.5ex plus .2ex}%
                                {\normalfont\normalsize\bfseries}}
\renewcommand{\subsubsection}{\@startsection{subsubsection}{3}{0mm}%
                                {-1ex plus -.5ex minus -.2ex}%
                                {1ex plus .2ex}%
                                {\normalfont\small\bfseries}}
\makeatother



% Don't print section numbers
\setcounter{secnumdepth}{0}


\setlength{\parindent}{0pt}
\setlength{\parskip}{0pt plus 0.5ex}


% -----------------------------------------------------------------------

\begin{document}

\SweaveOpts{concordance=TRUE}

\raggedright
\footnotesize
\begin{multicols}{3}


% multicol parameters
% These lengths are set only within the two main columns
%\setlength{\columnseprule}{0.25pt}
\setlength{\premulticols}{1pt}
\setlength{\postmulticols}{1pt}
\setlength{\multicolsep}{1pt}
\setlength{\columnsep}{2pt}

\begin{center}
     \Large{\textbf{rmongodb Cheat Sheet}} \\
     \small{\href{https://github.com/mongosoup/rmongodb}{https://github.com/mongosoup/rmongodb}}
\end{center}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Generall Package Handling}
Install from CRAN
<<eval=FALSE>>=
install.packages("rmongodb")
@
Install from GitHub
<<eval=FALSE>>=
library(devtools)
install_github("rmongodb", "mongosoup")
@
Load rmongodb package
<<>>=
library(rmongodb)
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Connection Handling}
connect to localhost
<<>>=
mongo <- mongo.create()
@
connect to extern
<<eval=FALSE>>=
mongo <- mongo.create(host="127.1.1.1", username="USER", 
                      password="XXX", db="database")
@
check for working connection
<<>>=
mongo.is.connected(mongo)
@
disconnect from mongodb
<<eval=FALSE>>=
mongo.destroy(mongo)
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Get Database Information}
get databases and collections
<<>>=
mongo.get.databases(mongo)
mongo.get.database.collections(mongo, "rmongodb")
@
get errors from mongodb
<<eval=FALSE>>=
mongo.get.err(mongo)
mongo.get.server.err(mongo)
mongo.get.server.err.string(mongo)
@
deal with replicas
<<eval=FALSE>>=
mongo.get.primary(mongo)
mongo.get.hosts(mongo)
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Querying Data}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Importing and Updating Data}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\rule{0.3\linewidth}{0.25pt}
\scriptsize

Copyright \copyright\ 2014 Markus Schmidberger

\href{https://github.com/mongosoup/rmongodb}{https://github.com/mongosoup/rmongodb}


\end{multicols}
\end{document}